/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    o: THREE.Mesh;
    n: THREE.Mesh;
  };
  materials: {
    ["SVGMat.001"]: THREE.MeshBasicMaterial;
  };
}

export function ModelLogo(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/logo.glb") as GLTFResult
  
  return (
    <group {...props} dispose={null} 
      // rotation={[Math.PI / 2, 0, 0]}  
      position={[0, -2.5, -0.35]} 
      scale={1.21}
    >
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials['SVGMat.001']} scale={11.794} />
      <mesh castShadow receiveShadow geometry={nodes.o.geometry} material={materials['SVGMat.001']} scale={11.794} />
      <mesh castShadow receiveShadow geometry={nodes.n.geometry} material={materials['SVGMat.001']} scale={11.794} />
    </group>
    
  )
}

useGLTF.preload('/logo.glb')